### ISSUE TITLE
Wireguard failure after Update

### ISSUE THREAD

**Issue by ElReyNCS** [YunoHost-Apps/wireguard_ynh#92]
### Describe the bug

I updated Wireguard via the system update. After that, I can neither access the app nor the domain.
Any attempts to uninstall the app or the domain to restore the backup were unsuccessful.

### Context

- Hardware: *VPS bought online 
- YunoHost version: 11.2.3 (stable)
- I have access to my server: *Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no

### Logs
https://paste.yunohost.org/raw/ugirijayif

### From Domain Sektion

Fehler: "500"

Aktion: "GET" /yunohost/api/domains/wguard.xxxx.de?locale=de

Fehlermeldung:
Unerwarteter Serverfehler

Zurück verfolgen

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 453, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 580, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/domain.py", line 170, in domain_info
    "name": app_info(app)["name"],
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 130, in app_info
    local_manifest = _get_manifest_of_app(setting_path)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 2157, in _get_manifest_of_app
    manifest = _convert_v1_manifest_to_v2(manifest)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 2278, in _convert_v1_manifest_to_v2
    install_questions = manifest["arguments"]["install"]
KeyError: 'arguments'

### Update via the terminal fails with the following result. 

Info: Now upgrading wireguard...
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 77, in <module>
    yunohost.cli(
  File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 41, in cli
    ret = moulinette.cli(
  File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 110, in cli
    Cli(
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 503, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 580, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 597, in app_upgrade
    app_dict = app_info(app_instance_name, full=True)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 130, in app_info
    local_manifest = _get_manifest_of_app(setting_path)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 2157, in _get_manifest_of_app
    manifest = _convert_v1_manifest_to_v2(manifest)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 2278, in _convert_v1_manifest_to_v2
    install_questions = manifest["arguments"]["install"]
KeyError: 'arguments'

**Comment by tituspijean** [comment]
Can you share the upgrade log? It looks like it downloaded the binary for the wrong architecture. Is your server AMD64?

**Comment by ElReyNCS** [comment]
Hello tituspijean,
thanks for the fast respond.

#### Is your server AMD64? 

Yes it is.
Typ: AMD EPYC 7702

#### Upgrade Log

https://paste.yunohost.org/raw/awexepemaf

Thank you.

**Comment by ElReyNCS** [comment]
#### Log from Wireguard-UI

https://paste.yunohost.org/raw/ilacuwihay

**Comment by ElReyNCS** [comment]
I dont get any further.
Wireguard works, the UI causes problems.
Any attempts to deinstall Wireguard or Wireguard-UI have failed.
I am thankful for every help.
